BASE_BUILDER = "BaseBuilder"
CODE_BUILDER = "CodeBuilder"
GENERATOR_BUILDER = "GeneratorBuilder"
OAI_THREAD_BUILDER = "OAIThreadBuilder"
BUILDERS = [CODE_BUILDER, GENERATOR_BUILDER, OAI_THREAD_BUILDER]
ALL_BUILDERS = BUILDERS + [BASE_BUILDER]